# Generated by Django 4.2.23 on 2025-08-07 20:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('playing', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, help_text='Link if the player will log in to score.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('tee_time', models.TimeField(blank=True, null=True)),
                ('players', models.ManyToManyField(blank=True, related_name='teams', to='outing.player')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole', models.PositiveSmallIntegerField()),
                ('strokes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outing.round')),
            ],
            options={
                'ordering': ['hole'],
                'unique_together': {('round', 'hole')},
            },
        ),
        migrations.AddField(
            model_name='round',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outing.team'),
        ),
        migrations.CreateModel(
            name='DriveUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='outing.player')),
                ('score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drive_used', to='outing.score')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('team', 'event_date')},
        ),
    ]
