# Generated by Django 4.2.23 on 2025-08-07 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='can_score',
            field=models.BooleanField(default=True, help_text="Allow this player to edit their team's scorecard."),
        ),
    ]
