# Generated by Django 4.2.23 on 2025-08-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outing', '0002_player_can_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18)], unique=True)),
                ('par', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['hole'],
            },
        ),
    ]
