# Generated by Django 4.2.23 on 2025-08-08 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outing', '0003_coursepar'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(default='Beer Open', max_length=80)),
                ('event_date', models.DateField(default=datetime.date.today)),
                ('leaderboard_public', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Event settings',
                'verbose_name_plural': 'Event settings',
            },
        ),
    ]
