# Generated by Django 4.2.23 on 2025-08-09 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outing', '0005_magiclogintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_rounds', to=settings.AUTH_USER_MODEL),
        ),
    ]
