# Generated by Django 4.2.23 on 2025-08-11 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outing', '0006_round_finalized_at_round_finalized_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='shirt_size',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.CreateModel(
            name='SMSResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('from_number', models.CharField(max_length=20)),
                ('message_body', models.TextField()),
                ('campaign', models.CharField(blank=True, max_length=40)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='outing.player')),
            ],
        ),
    ]
