# Generated by Django 4.2.23 on 2025-08-19 18:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('outing', '0007_player_shirt_size_smsresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('open', 'Open'), ('ito', 'Ito'), ('local', 'Local')], default='open', max_length=16)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='archive/%Y/logo/')),
                ('plaque', models.ImageField(blank=True, upload_to='archive/%Y/plaque/')),
                ('writeup_md', models.TextField(blank=True)),
                ('odds_md', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'kind'],
                'unique_together': {('year', 'kind')},
            },
        ),
        migrations.CreateModel(
            name='ArchiveImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='archive/%Y/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='outing.archiveevent')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
