# Generated by Django 4.2.23 on 2025-08-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outing', '0008_archiveevent_archiveimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveevent',
            name='logo',
            field=models.CharField(blank=True, help_text='Relative static path, e.g. outing/archive/2024/BeerOpen2024.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='archiveevent',
            name='plaque',
            field=models.CharField(blank=True, help_text='Relative static path, e.g. outing/archive/2024/plaque.jpg', max_length=255),
        ),
        migrations.AlterField(
            model_name='archiveimage',
            name='image',
            field=models.CharField(help_text='Relative static path, e.g. outing/archive/2024/gallery/01.jpg', max_length=255),
        ),
    ]
