# Generated by Django 4.2.23 on 2025-08-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outing', '0009_alter_archiveevent_logo_alter_archiveevent_plaque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveevent',
            name='p1_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archiveevent',
            name='p1_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archiveevent',
            name='p2_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archiveevent',
            name='p2_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archiveevent',
            name='p3_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archiveevent',
            name='p3_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archiveevent',
            name='p4_first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archiveevent',
            name='p4_last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='archiveevent',
            name='swag',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
