# Generated by Django 4.2.23 on 2025-08-29 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outing', '0010_archiveevent_p1_first_name_archiveevent_p1_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('par', models.PositiveSmallIntegerField()),
                ('men_hdcp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wom_hdcp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holes', to='outing.course')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('course', 'number')},
            },
        ),
        migrations.CreateModel(
            name='TeeBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('slope', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tees', to='outing.course')),
            ],
            options={
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TeeYardage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yards', models.PositiveIntegerField()),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yardages', to='outing.hole')),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yardages', to='outing.teebox')),
            ],
            options={
                'unique_together': {('tee', 'hole')},
            },
        ),
    ]
