# Generated by Django 4.2.23 on 2025-08-29 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outing', '0011_course_hole_teebox_teeyardage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='scoring_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='outing.course'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='scoring_tee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='outing.teebox'),
        ),
    ]
