# Generated by Django 4.2.23 on 2025-08-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outing', '0012_eventsettings_scoring_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teeyardage',
            name='designation',
            field=models.CharField(blank=True, choices=[('blue', 'Blue'), ('white', 'White')], help_text='For combo tees like Blue/White, which base tee was used on this hole.', max_length=16),
        ),
    ]
